### ISSUE TITLE
Error: Not found: 'dart:js' and Error: Not found: 'dart:html' and Error: Type 'JsObject' not found.

### ISSUE THREAD

**Issue by JordyBanany** [shripal17/dart_scorm#1]
Error: Not found: 'dart:js' and Error: Not found: 'dart:html' and Error: Type 'JsObject' not found on scorm.api file.

when running the app.

tried replacing with import 'package:js/js.dart'; and import 'package:html/dom.dart';
but the  Error: Type 'JsObject' still persists.

is this package compatible with flutter 2 onwards?

tried on Stable 2.0.6, 2.0.0, 1.22.6, and 1.17.1
and Beta 2.2.0-10.3.pre

same errors on 2.2.0-10.3.pre, 2.0.6, and 2.0.0
wont work on 1.22.6, and 1.17.1, says require higher flutter sdk version

**Comment by shripal17** [comment]
Hi,

The package is not null-safe, but it should work with Flutter 2.0.

Have you enabled web support for your app?

I had made this on Flutter stable 1.22.x

**Comment by shripal17** [comment]
Also, it does not require Flutter. It should work even with a standalone dart web app

**Comment by JordyBanany** [comment]
ohhh, my bad. 

i did not realize it only works on flutter web. I keep trying it on an android emulator.

it runs on chrome now.

**Comment by shripal17** [comment]
No problem, closing this issue. 

Feel free to re-open this one, or a new one if you face any more issues.
